/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.selecciones.formas;


import java.util.Enumeration;
import java.util.LinkedList;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import uam.pvoe.sw.selecciones.clases.Alumno;
import uam.pvoe.sw.selecciones.clases.Licenciatura;
import uam.pvoe.sw.selecciones.clases.Opcion;
import uam.pvoe.sw.selecciones.negocio.AdministrarAlumnos;
import uam.pvoe.sw.selecciones.negocio.AdministrarLicenciaturas;




/**
 *
 * @author josue
 */
public class FrmSeleccionesObjetos extends javax.swing.JFrame {

    LinkedList<JCheckBox>listaChkBoxes = new LinkedList();
    
    /**
     * Creates new form FrmSeleccionesObjetos
     */
        public FrmSeleccionesObjetos() {
            initComponents();
            agruparSelecciones();
            agruparChkBoxes();
            cmbListaAlumnos.removeAllItems();
            cmbListaLicenciaturas.removeAllItems();
            llenarLicenciaturas();
            llenarBotonesMerece();
            llenarCheckBoxes(); 
            ocultarTodoElementos();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpApoyo = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblLicenciatura = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();
        cmbListaLicenciaturas = new javax.swing.JComboBox<>();
        cmbListaAlumnos = new javax.swing.JComboBox<>();
        btnMerece = new javax.swing.JRadioButton();
        btnNoMerece = new javax.swing.JRadioButton();
        chkPronabe = new javax.swing.JCheckBox();
        chkUam = new javax.swing.JCheckBox();
        chkCDMX = new javax.swing.JCheckBox();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));

        lblTitulo.setText("Sistema de Apoyos Económicos para Alumnos");

        lblLicenciatura.setText("Selecciona la Licenciatura");

        lblAlumno.setText("Selecciona el Alumno");

        cmbListaLicenciaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListaLicenciaturasActionPerformed(evt);
            }
        });

        btnMerece.setText("jRadioButton1");
        btnMerece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMereceActionPerformed(evt);
            }
        });

        btnNoMerece.setText("jRadioButton1");
        btnNoMerece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoMereceActionPerformed(evt);
            }
        });

        chkPronabe.setText("jCheckBox1");

        chkUam.setText("jCheckBox1");

        chkCDMX.setText("jCheckBox1");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTitulo)
                        .addComponent(lblLicenciatura)
                        .addComponent(lblAlumno)
                        .addComponent(cmbListaLicenciaturas, 0, 344, Short.MAX_VALUE)
                        .addComponent(cmbListaAlumnos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMerece)
                            .addComponent(btnNoMerece))
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCDMX)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkPronabe)
                                .addGap(53, 53, 53)
                                .addComponent(chkUam)))))
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(49, 49, 49)
                .addComponent(lblLicenciatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbListaLicenciaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lblAlumno)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbListaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnMerece))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkPronabe)
                            .addComponent(chkUam))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNoMerece)
                    .addComponent(chkCDMX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbListaLicenciaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListaLicenciaturasActionPerformed
        // TODO add your handling code here:
        mostrarListaAlumnos();
    }//GEN-LAST:event_cmbListaLicenciaturasActionPerformed
    
    public void mostrarListaAlumnos(){
        
        Licenciatura licenciatura = (Licenciatura) cmbListaLicenciaturas.getSelectedItem(); 
//        System.out.println(licenciatura.getNombre());
//        System.out.println(licenciatura.getClave());
        
        int indice = cmbListaLicenciaturas.getSelectedIndex(); 
        if(indice != 0){
            lblAlumno.setVisible(true);
            cmbListaAlumnos.removeAllItems();
            llenarListaAlumnos(licenciatura.getClave());
            cmbListaAlumnos.setVisible(true); 
            btnMerece.setVisible(true); 
            btnNoMerece.setVisible(true); 
            btnRegistrar.setVisible(true); 
            
        }else{
           limpiarCampos(); 
           ocultarTodoElementos();
        }
        
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        //mostramos la clave de la licenciatura
        System.out.println("----------------------------------- ALUMNO REGISTRADO ----------------------------------------");
        Licenciatura lic = (Licenciatura)cmbListaLicenciaturas.getSelectedItem(); 
        System.out.println("CLAVE LICENCIATURA: " + lic.getClave());
        Alumno alumno = (Alumno)cmbListaAlumnos.getSelectedItem(); 
        System.out.println("MATRICULA DEL ALUMNO: " + alumno.getMatricula());
        
        //PARA REVISAR SI QUIERE APOYO O NO 
        Enumeration<AbstractButton> btnGrp = btnGrpApoyo.getElements(); 
        while(btnGrp.hasMoreElements()){
            JRadioButton btnAux = (JRadioButton) btnGrp.nextElement(); 
            if(btnAux.isSelected()){
                Opcion resultado = (Opcion) btnAux.getClientProperty("key");
                System.out.println("EVALUACION DE APOYO:  " + resultado.getValor());
                if(resultado.getLlave().equals("MERECE")){
                    System.out.println("APOYOS:");
                    for(int i = 0; i < listaChkBoxes.size(); ++i){
                        JCheckBox aux = listaChkBoxes.get(i); 
                        if(aux.isSelected()){
                            Opcion opcion = (Opcion) aux.getClientProperty("llave"); 
                            System.out.println(opcion.getLlave());
                        }
                    }
                }
            }
        }
        
        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMereceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMereceActionPerformed
        // TODO add your handling code here:
        visibilidadApoyos(true);
    }//GEN-LAST:event_btnMereceActionPerformed

    private void btnNoMereceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoMereceActionPerformed
        // TODO add your handling code here:
        limpiarCampos(); 
        visibilidadApoyos(false);
    }//GEN-LAST:event_btnNoMereceActionPerformed
    public void llenarLicenciaturas(){
        AdministrarLicenciaturas administrar = new AdministrarLicenciaturas(); 
        LinkedList<Licenciatura> lista = administrar.listaLicenciaturas(); 
        
        for(int i = 0; i < lista.size(); ++i){
            Licenciatura licenciatura = lista.get(i); 
            cmbListaLicenciaturas.addItem(licenciatura);
        }
    }
    
    public void llenarListaAlumnos(String clave){
        AdministrarAlumnos administrar = new AdministrarAlumnos(); 
        LinkedList<Alumno> lista = administrar.listaPorCarrera(clave); 
        for(int i = 0; i < lista.size(); ++i){
            Alumno alumno = lista.get(i); 
            cmbListaAlumnos.addItem(alumno);
        }
    }
    
    public void llenarBotonesMerece(){
        Opcion merece = new Opcion("MERECE", "Merecedor de apoyos"); 
        Opcion noMerece = new Opcion("NO_MERECE", "No es merecedor de apoyos"); 
        
        btnMerece.setText(merece.getValor());
        btnNoMerece.setText(noMerece.getValor());
        
        btnMerece.putClientProperty("key", merece);
        btnNoMerece.putClientProperty("key", noMerece);
        
        btnNoMerece.setSelected(true);
    }
    
    public void llenarCheckBoxes(){
        Opcion opcionA = new Opcion("PRONABE", "Beca de gobierno"); 
        Opcion opcionB = new Opcion("UAM", "Beca de la UAM"); 
        Opcion opcionC = new Opcion("CDMX", "Beca de la ciudad de México"); 
        
        chkCDMX.putClientProperty("llave", opcionC);
        chkPronabe.putClientProperty("llave", opcionA);
        chkUam.putClientProperty("llave", opcionB);
        
        chkCDMX.setText(opcionC.getValor());
        chkPronabe.setText(opcionA.getValor());
        chkUam.setText(opcionB.getValor());
    }
    
    public void ocultarTodoElementos(){
        lblAlumno.setVisible(false); 
        cmbListaAlumnos.setVisible(false);
        btnMerece.setVisible(false); 
        btnNoMerece.setVisible(false); 
        chkCDMX.setVisible(false); 
        chkUam.setVisible(false);
        chkPronabe.setVisible(false);
        btnRegistrar.setVisible(false); 
    }
    
    public void visibilidadApoyos(boolean visibilidad){
        chkCDMX.setVisible(visibilidad);
        chkPronabe.setVisible(visibilidad);
        chkUam.setVisible(visibilidad);
                
    }
    
    public void limpiarCampos(){
        chkCDMX.setSelected(false);
        chkPronabe.setSelected(false); 
        chkUam.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionesObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionesObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionesObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionesObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSeleccionesObjetos().setVisible(true);
            }
        });
    }
    
    /*Agrupa los Radio Buttons*/
    public void agruparSelecciones(){
        btnGrpApoyo.add(btnMerece);
        btnGrpApoyo.add(btnNoMerece);
       
    }
    
    /*Agrupa los CheckBoxes*/
    public void agruparChkBoxes(){
        listaChkBoxes.add(chkUam);
        listaChkBoxes.add(chkCDMX);
        listaChkBoxes.add(chkPronabe);
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpApoyo;
    private javax.swing.JRadioButton btnMerece;
    private javax.swing.JRadioButton btnNoMerece;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chkCDMX;
    private javax.swing.JCheckBox chkPronabe;
    private javax.swing.JCheckBox chkUam;
    private javax.swing.JComboBox<Alumno> cmbListaAlumnos;
    private javax.swing.JComboBox<Licenciatura> cmbListaLicenciaturas;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblLicenciatura;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
